"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = ['maldonadocorretorimoveis.com.br', 'www.maldonadocorretorimoveis.com.br']
CORS_ALLOWED_ORIGINS = ['https://maldonadocorretorimoveis.com.br', 'https://www.maldonadocorretorimoveis.com.br']
CSRF_TRUSTED_ORIGINS = ['https://maldonadocorretorimoveis.com.br', 'https://www.maldonadocorretorimoveis.com.br']
CORS_ALLOW_CREDENTIALS = True


APPEND_SLASH = False

GEOAPIFY_API_KEY = os.getenv('GEOAPIFY_API_KEY', '')
FOURSQUARE_API_KEY = os.getenv('FOURSQUARE_API_KEY', '')
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "").strip()
SITE_DOMAIN = "maldonadocorretorimoveis.com.br"
PUBLIC_BASE_URL = f"https://{SITE_DOMAIN}"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'imoveis'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'imoveis.middleware.ContentSecurityPolicyMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'imoveis' / 'Controller' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER': os.getenv("POSTGRES_USER"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': os.getenv("POSTGRES_HOST", "localhost"),
        'PORT': os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
FRONTEND_DIST_DIR = BASE_DIR / 'frontend' / 'dist'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'imoveis.authentication.CookieJWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'imoveis.nao_autorizado.handler',
}

JWT_AUTH_COOKIE = os.getenv("JWT_AUTH_COOKIE", "maldonado_access")
JWT_REFRESH_COOKIE = os.getenv("JWT_REFRESH_COOKIE", "maldonado_refresh")
JWT_AUTH_COOKIE_SAMESITE = os.getenv("JWT_AUTH_COOKIE_SAMESITE", "Lax")
JWT_AUTH_COOKIE_SECURE = os.getenv("JWT_AUTH_COOKIE_SECURE", "True").lower() in {"1", "true", "yes", "on"}
JWT_AUTH_COOKIE_DOMAIN = os.getenv("JWT_AUTH_COOKIE_DOMAIN") or None

RATELIMIT_ENABLE = os.getenv("DJANGO_RATELIMIT_ENABLE", "True").lower() in {"1", "true", "yes", "on"}
RATELIMIT_RATES = {
    "auth.login.ip": os.getenv("RATELIMIT_AUTH_LOGIN", "5/m"),
    "auth.register.ip": os.getenv("RATELIMIT_AUTH_REGISTER", "3/h"),
    "auth.password_reset.ip": os.getenv("RATELIMIT_AUTH_PASSWORD_RESET", "5/h"),
    "auth.refresh.ip": os.getenv("RATELIMIT_AUTH_REFRESH", "20/m"),
    "api.public.ip": os.getenv("RATELIMIT_API_PUBLIC", "120/m"),
    "api.search.ip": os.getenv("RATELIMIT_API_SEARCH", "30/m"),
    "api.user.ip": os.getenv("RATELIMIT_API_USER", "60/m"),
    "api.admin.ip": os.getenv("RATELIMIT_API_ADMIN", "80/m"),
    "api.admin.write.ip": os.getenv("RATELIMIT_API_ADMIN_WRITE", "20/m"),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  #token de acesso expira em 30 minutos:  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     #refresh Token  expira em 1 dia:
    'AUTH_HEADER_TYPES': ('Bearer',),
}




SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "True").lower() in {"1", "true", "yes", "on"}
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "True").lower() in {"1", "true", "yes", "on"}
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "True").lower() in {"1", "true", "yes", "on"}
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if not DEBUG else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "True").lower() in {"1", "true", "yes", "on"}
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "True").lower() in {"1", "true", "yes", "on"}
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE", str(32 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))

REDIS_URL = os.getenv("REDIS_URL", "").strip()
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }

CONTENT_SECURITY_POLICY = os.getenv(
    "CONTENT_SECURITY_POLICY",
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline'; "
    "style-src 'self' 'unsafe-inline' https://unpkg.com; "
    "img-src 'self' data: blob: https://*.tile.openstreetmap.org https://*.basemaps.cartocdn.com https://*.cartocdn.com https://server.arcgisonline.com; "
    "font-src 'self' data:; "
    "connect-src 'self' https://nominatim.openstreetmap.org https://overpass-api.de https://api.geoapify.com https://api.foursquare.com; "
    "media-src 'self' blob:; "
    "frame-src 'self' https://www.openstreetmap.org; "
    "frame-ancestors 'none'; "
    "base-uri 'self'; "
    "form-action 'self'",
)


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
EMAIL_USE_SSL = EMAIL_PORT == 465
EMAIL_USE_TLS = not EMAIL_USE_SSL
EMAIL_TIMEOUT = 10
