# Generated by Django 6.0.5 on 2026-05-12 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('codigo_ibge', models.CharField(blank=True, max_length=20, verbose_name='Codigo IBGE')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('pontos_sincronizados_em', models.DateTimeField(blank=True, null=True, verbose_name='Pontos sincronizados em')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(help_text='Ex: 5511999999999', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('creci', models.CharField(blank=True, max_length=50, verbose_name='CRECI')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='corretores/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Imovel',
                'verbose_name_plural': 'Tipos de Imovel',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros', to='imoveis.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Preco (R$)')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereco completo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('quartos', models.PositiveIntegerField(default=0, verbose_name='Quartos')),
                ('banheiros', models.PositiveIntegerField(default=0, verbose_name='Banheiros')),
                ('vagas', models.PositiveIntegerField(default=0, verbose_name='Vagas de garagem')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area (m2)')),
                ('status', models.CharField(choices=[('disponivel', 'Disponivel'), ('vendido', 'Vendido'), ('alugado', 'Alugado'), ('reservado', 'Reservado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('destaque', models.BooleanField(default=False, verbose_name='Imovel em destaque')),
                ('zona_uso', models.CharField(blank=True, max_length=50, verbose_name='Zona de uso')),
                ('topografia', models.CharField(blank=True, choices=[('plana', 'Plana'), ('aclive', 'Aclive'), ('declive', 'Declive'), ('irregular', 'Irregular')], max_length=50, verbose_name='Topografia')),
                ('finalidade', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('misto', 'Misto'), ('industrial', 'Industrial')], max_length=50, verbose_name='Finalidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.bairro', verbose_name='Bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cidade', verbose_name='Cidade')),
                ('corretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.corretor', verbose_name='Corretor')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.tipoimovel', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Imovel',
                'verbose_name_plural': 'Imoveis',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem principal')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel', verbose_name='Imovel')),
            ],
            options={
                'verbose_name': 'Imagem do Imovel',
                'verbose_name_plural': 'Imagens do Imovel',
                'ordering': ['-principal', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='FavoritoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis_favoritos', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='imoveis.imovel')),
            ],
            options={
                'verbose_name': 'Imovel Favorito',
                'verbose_name_plural': 'Imoveis Favoritos',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'imovel')},
            },
        ),
        migrations.CreateModel(
            name='PontoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(max_length=20, verbose_name='Tipo OSM')),
                ('osm_id', models.CharField(max_length=40, verbose_name='ID OSM')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('restaurante', 'Restaurante'), ('mercado', 'Mercado'), ('loja', 'Loja'), ('turismo', 'Turismo'), ('parque', 'Parque'), ('servico', 'Servico')], max_length=30, verbose_name='Categoria')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='Tags')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_interesse', to='imoveis.cidade')),
            ],
            options={
                'verbose_name': 'Ponto de Interesse',
                'verbose_name_plural': 'Pontos de Interesse',
                'ordering': ['categoria', 'nome'],
                'unique_together': {('cidade', 'osm_type', 'osm_id')},
            },
        ),
    ]
