# Generated by Django 6.0.5 on 2026-05-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_endereco_busca_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='LembreteFavoritosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_mensagem', models.TextField(default='Ola, tenho interesse no imovel {titulo}: {url}', help_text='Variaveis disponiveis: {titulo}, {url}, {preco}, {endereco}.', verbose_name='Mensagem do WhatsApp')),
                ('horario', models.TimeField(default='09:00', verbose_name='Horario de envio')),
                ('ativo', models.BooleanField(default=False, verbose_name='Agendamento ativo')),
                ('cron_instalado', models.BooleanField(default=False, verbose_name='Cron instalado')),
                ('cron_linha', models.TextField(blank=True, verbose_name='Linha do cron')),
                ('ultima_atualizacao_cron', models.DateTimeField(blank=True, null=True, verbose_name='Ultima atualizacao do cron')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuracao de Lembrete de Favoritos',
                'verbose_name_plural': 'Configuracoes de Lembretes de Favoritos',
            },
        ),
    ]
