# Generated by Django 6.0.5 on 2026-05-18 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_lembretefavoritosconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembretefavoritosconfig',
            name='horario',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Horario de envio'),
        ),
    ]
