# Generated by Django 6.0.5 on 2026-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_lembretefavoritosconfig_whatsapp_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('route', models.CharField(blank=True, max_length=200)),
                ('erro', models.TextField()),
            ],
        ),
    ]
