from django.urls import path

from .views import (
    ApiBuscarEnderecoView,
    ApiCepCadastroView,
    ApiBuscarPontosInteresseView,
    ApiCidadeDetailView,
    ApiCidadesView,
    ApiCorretorDetailView,
    ApiCorretoresView,
    ApiFavoritoDetailView,
    ApiFavoritosView,
    ApiImovelDetailView,
    ApiImovelUuidDetailView,
    ApiImoveisView,
    ApiIntegracoesHealthView,
    ApiLembreteFavoritosView,
    ApiLogsView,
    ApiReverseEnderecoView,
    ApiStatsView,
    ApiUsuarioDetailView,
    ApiUsuarioResetLinkView,
    ApiUsuariosView,
    GetCidadeInfoCep,
)

urlpatterns = [
    path("api/get/cidade/cep/", GetCidadeInfoCep, name="GetCidadeCep"),
    path("api/stats/", ApiStatsView, name="ApiStats"),
    path("api/logs/", ApiLogsView, name="ApiLogs"),
    path("api/imoveis/", ApiImoveisView, name="ApiImoveis"),
    path("api/imoveis/<int:pk>/", ApiImovelDetailView, name="ApiImovelDetail"),
    path("api/imoveis/<uuid:uuid>/", ApiImovelUuidDetailView, name="ApiImovelUuidDetail"),
    path("api/favoritos/", ApiFavoritosView, name="ApiFavoritos"),
    path("api/favoritos/<int:imovel_id>/", ApiFavoritoDetailView, name="ApiFavoritoDetail"),
    path("api/integracoes/health/", ApiIntegracoesHealthView, name="ApiIntegracoesHealth"),
    path("api/lembrete-favoritos/", ApiLembreteFavoritosView, name="ApiLembreteFavoritos"),
    path("api/cep/<str:cep>/", ApiCepCadastroView, name="ApiCepCadastro"),
    path("api/buscar-endereco/", ApiBuscarEnderecoView, name="ApiBuscarEndereco"),
    path("api/reverse-endereco/", ApiReverseEnderecoView, name="ApiReverseEndereco"),
    path("api/pontos-interesse/", ApiBuscarPontosInteresseView, name="ApiBuscarPontosInteresse"),
    path("api/corretores/", ApiCorretoresView, name="ApiCorretores"),
    path("api/corretores/<int:pk>/", ApiCorretorDetailView, name="ApiCorretorDetail"),
    path("api/usuarios/", ApiUsuariosView, name="ApiUsuarios"),
    path("api/usuarios/<int:user_id>/", ApiUsuarioDetailView, name="ApiUsuarioDetail"),
    path("api/usuarios/<int:user_id>/reset-link/", ApiUsuarioResetLinkView, name="ApiUsuarioResetLink"),
    path("api/cidades/", ApiCidadesView, name="ApiCidades"),
    path("api/cidades/<int:pk>/", ApiCidadeDetailView, name="ApiCidadeDetail"),
]
